<?php
/**
 * File for the class which returns the class map definition
 * @package Magento
 * @date 2013-09-04
 * @author Mikaël DELSOL <contact@wsdltophp.com>
 */
/**
 * Class which returns the class map definition by the static method MagentoClassMap::classMap()
 * @package Magento
 * @date 2013-09-04
 * @author Mikaël DELSOL <contact@wsdltophp.com>
 */
class MagentoClassMap
{
	/**
	 * This method returns the array containing the mapping between WSDL structs and generated classes
	 * This array is sent to the SoapClient when calling the WS
	 * @return array
	 */
	final public static function classMap()
	{
		return array (
  'Array' => 'MagentoStructArray',
  'ENTITIES' => 'MagentoStructENTITIES',
  'ENTITY' => 'MagentoStructENTITY',
  'ID' => 'MagentoStructID',
  'IDREF' => 'MagentoStructIDREF',
  'IDREFS' => 'MagentoStructIDREFS',
  'NCName' => 'MagentoStructNCName',
  'NMTOKEN' => 'MagentoStructNMTOKEN',
  'NMTOKENS' => 'MagentoStructNMTOKENS',
  'NOTATION' => 'MagentoStructNOTATION',
  'Name' => 'MagentoStructName',
  'QName' => 'MagentoStructQName',
  'Struct' => 'MagentoStructStruct',
  'anyURI' => 'MagentoStructAnyURI',
  'apiEntity' => 'MagentoStructApiEntity',
  'apiMethodEntity' => 'MagentoStructApiMethodEntity',
  'associativeEntity' => 'MagentoStructAssociativeEntity',
  'associativeMultiEntity' => 'MagentoStructAssociativeMultiEntity',
  'base64Binary' => 'MagentoStructBase64Binary',
  'boolean' => 'MagentoStructBoolean',
  'byte' => 'MagentoStructByte',
  'catalogAssignedProduct' => 'MagentoStructCatalogAssignedProduct',
  'catalogAttributeEntity' => 'MagentoStructCatalogAttributeEntity',
  'catalogAttributeOptionEntity' => 'MagentoStructCatalogAttributeOptionEntity',
  'catalogCategoryEntity' => 'MagentoStructCatalogCategoryEntity',
  'catalogCategoryEntityCreate' => 'MagentoStructCatalogCategoryEntityCreate',
  'catalogCategoryEntityNoChildren' => 'MagentoStructCatalogCategoryEntityNoChildren',
  'catalogCategoryInfo' => 'MagentoStructCatalogCategoryInfo',
  'catalogCategoryTree' => 'MagentoStructCatalogCategoryTree',
  'catalogInventoryStockItemEntity' => 'MagentoStructCatalogInventoryStockItemEntity',
  'catalogInventoryStockItemUpdateEntity' => 'MagentoStructCatalogInventoryStockItemUpdateEntity',
  'catalogProductAdditionalAttributesEntity' => 'MagentoStructCatalogProductAdditionalAttributesEntity',
  'catalogProductAttributeEntity' => 'MagentoStructCatalogProductAttributeEntity',
  'catalogProductAttributeEntityToCreate' => 'MagentoStructCatalogProductAttributeEntityToCreate',
  'catalogProductAttributeEntityToUpdate' => 'MagentoStructCatalogProductAttributeEntityToUpdate',
  'catalogProductAttributeFrontendLabelEntity' => 'MagentoStructCatalogProductAttributeFrontendLabelEntity',
  'catalogProductAttributeMediaCreateEntity' => 'MagentoStructCatalogProductAttributeMediaCreateEntity',
  'catalogProductAttributeMediaTypeEntity' => 'MagentoStructCatalogProductAttributeMediaTypeEntity',
  'catalogProductAttributeOptionEntityToAdd' => 'MagentoStructCatalogProductAttributeOptionEntityToAdd',
  'catalogProductAttributeOptionLabelEntity' => 'MagentoStructCatalogProductAttributeOptionLabelEntity',
  'catalogProductAttributeSetEntity' => 'MagentoStructCatalogProductAttributeSetEntity',
  'catalogProductCreateEntity' => 'MagentoStructCatalogProductCreateEntity',
  'catalogProductCustomOptionAdditionalFieldsEntity' => 'MagentoStructCatalogProductCustomOptionAdditionalFieldsEntity',
  'catalogProductCustomOptionInfoEntity' => 'MagentoStructCatalogProductCustomOptionInfoEntity',
  'catalogProductCustomOptionListEntity' => 'MagentoStructCatalogProductCustomOptionListEntity',
  'catalogProductCustomOptionToAdd' => 'MagentoStructCatalogProductCustomOptionToAdd',
  'catalogProductCustomOptionToUpdate' => 'MagentoStructCatalogProductCustomOptionToUpdate',
  'catalogProductCustomOptionTypesEntity' => 'MagentoStructCatalogProductCustomOptionTypesEntity',
  'catalogProductCustomOptionValueAddEntity' => 'MagentoStructCatalogProductCustomOptionValueAddEntity',
  'catalogProductCustomOptionValueInfoEntity' => 'MagentoStructCatalogProductCustomOptionValueInfoEntity',
  'catalogProductCustomOptionValueListEntity' => 'MagentoStructCatalogProductCustomOptionValueListEntity',
  'catalogProductCustomOptionValueUpdateEntity' => 'MagentoStructCatalogProductCustomOptionValueUpdateEntity',
  'catalogProductDownloadableLinkAddEntity' => 'MagentoStructCatalogProductDownloadableLinkAddEntity',
  'catalogProductDownloadableLinkAddSampleEntity' => 'MagentoStructCatalogProductDownloadableLinkAddSampleEntity',
  'catalogProductDownloadableLinkEntity' => 'MagentoStructCatalogProductDownloadableLinkEntity',
  'catalogProductDownloadableLinkFileEntity' => 'MagentoStructCatalogProductDownloadableLinkFileEntity',
  'catalogProductDownloadableLinkFileInfoEntity' => 'MagentoStructCatalogProductDownloadableLinkFileInfoEntity',
  'catalogProductDownloadableLinkInfoEntity' => 'MagentoStructCatalogProductDownloadableLinkInfoEntity',
  'catalogProductDownloadableLinkSampleEntity' => 'MagentoStructCatalogProductDownloadableLinkSampleEntity',
  'catalogProductEntity' => 'MagentoStructCatalogProductEntity',
  'catalogProductImageEntity' => 'MagentoStructCatalogProductImageEntity',
  'catalogProductImageFileEntity' => 'MagentoStructCatalogProductImageFileEntity',
  'catalogProductLinkAttributeEntity' => 'MagentoStructCatalogProductLinkAttributeEntity',
  'catalogProductLinkEntity' => 'MagentoStructCatalogProductLinkEntity',
  'catalogProductRequestAttributes' => 'MagentoStructCatalogProductRequestAttributes',
  'catalogProductReturnEntity' => 'MagentoStructCatalogProductReturnEntity',
  'catalogProductTagAddEntity' => 'MagentoStructCatalogProductTagAddEntity',
  'catalogProductTagInfoEntity' => 'MagentoStructCatalogProductTagInfoEntity',
  'catalogProductTagListEntity' => 'MagentoStructCatalogProductTagListEntity',
  'catalogProductTagUpdateEntity' => 'MagentoStructCatalogProductTagUpdateEntity',
  'catalogProductTierPriceEntity' => 'MagentoStructCatalogProductTierPriceEntity',
  'catalogProductTypeEntity' => 'MagentoStructCatalogProductTypeEntity',
  'complexFilter' => 'MagentoStructComplexFilter',
  'customerAddressEntityCreate' => 'MagentoStructCustomerAddressEntityCreate',
  'customerAddressEntityItem' => 'MagentoStructCustomerAddressEntityItem',
  'customerCustomerEntity' => 'MagentoStructCustomerCustomerEntity',
  'customerCustomerEntityToCreate' => 'MagentoStructCustomerCustomerEntityToCreate',
  'customerGroupEntity' => 'MagentoStructCustomerGroupEntity',
  'date' => 'MagentoStructDate',
  'dateTime' => 'MagentoStructDateTime',
  'decimal' => 'MagentoStructDecimal',
  'directoryCountryEntity' => 'MagentoStructDirectoryCountryEntity',
  'directoryRegionEntity' => 'MagentoStructDirectoryRegionEntity',
  'double' => 'MagentoStructDouble',
  'duration' => 'MagentoStructDuration',
  'existsFaltureEntity' => 'MagentoStructExistsFaltureEntity',
  'filters' => 'MagentoStructFilters',
  'float' => 'MagentoStructFloat',
  'gDay' => 'MagentoStructGDay',
  'gMonth' => 'MagentoStructGMonth',
  'gMonthDay' => 'MagentoStructGMonthDay',
  'gYear' => 'MagentoStructGYear',
  'gYearMonth' => 'MagentoStructGYearMonth',
  'giftMessageAssociativeProductsEntity' => 'MagentoStructGiftMessageAssociativeProductsEntity',
  'giftMessageEntity' => 'MagentoStructGiftMessageEntity',
  'giftMessageResponse' => 'MagentoStructGiftMessageResponse',
  'hexBinary' => 'MagentoStructHexBinary',
  'int' => 'MagentoStructInt',
  'integer' => 'MagentoStructInteger',
  'language' => 'MagentoStructLanguage',
  'long' => 'MagentoStructLong',
  'magentoInfoEntity' => 'MagentoStructMagentoInfoEntity',
  'negativeInteger' => 'MagentoStructNegativeInteger',
  'nonNegativeInteger' => 'MagentoStructNonNegativeInteger',
  'nonPositiveInteger' => 'MagentoStructNonPositiveInteger',
  'normalizedString' => 'MagentoStructNormalizedString',
  'orderItemIdQty' => 'MagentoStructOrderItemIdQty',
  'positiveInteger' => 'MagentoStructPositiveInteger',
  'salesOrderAddressEntity' => 'MagentoStructSalesOrderAddressEntity',
  'salesOrderCreditmemoCommentEntity' => 'MagentoStructSalesOrderCreditmemoCommentEntity',
  'salesOrderCreditmemoData' => 'MagentoStructSalesOrderCreditmemoData',
  'salesOrderCreditmemoEntity' => 'MagentoStructSalesOrderCreditmemoEntity',
  'salesOrderCreditmemoItemEntity' => 'MagentoStructSalesOrderCreditmemoItemEntity',
  'salesOrderEntity' => 'MagentoStructSalesOrderEntity',
  'salesOrderInvoiceCommentEntity' => 'MagentoStructSalesOrderInvoiceCommentEntity',
  'salesOrderInvoiceEntity' => 'MagentoStructSalesOrderInvoiceEntity',
  'salesOrderInvoiceItemEntity' => 'MagentoStructSalesOrderInvoiceItemEntity',
  'salesOrderItemEntity' => 'MagentoStructSalesOrderItemEntity',
  'salesOrderListEntity' => 'MagentoStructSalesOrderListEntity',
  'salesOrderPaymentEntity' => 'MagentoStructSalesOrderPaymentEntity',
  'salesOrderShipmentCommentEntity' => 'MagentoStructSalesOrderShipmentCommentEntity',
  'salesOrderShipmentEntity' => 'MagentoStructSalesOrderShipmentEntity',
  'salesOrderShipmentItemEntity' => 'MagentoStructSalesOrderShipmentItemEntity',
  'salesOrderShipmentTrackEntity' => 'MagentoStructSalesOrderShipmentTrackEntity',
  'salesOrderStatusHistoryEntity' => 'MagentoStructSalesOrderStatusHistoryEntity',
  'shoppingCartAddressEntity' => 'MagentoStructShoppingCartAddressEntity',
  'shoppingCartCustomerAddressEntity' => 'MagentoStructShoppingCartCustomerAddressEntity',
  'shoppingCartCustomerEntity' => 'MagentoStructShoppingCartCustomerEntity',
  'shoppingCartInfoEntity' => 'MagentoStructShoppingCartInfoEntity',
  'shoppingCartItemEntity' => 'MagentoStructShoppingCartItemEntity',
  'shoppingCartLicenseEntity' => 'MagentoStructShoppingCartLicenseEntity',
  'shoppingCartPaymentEntity' => 'MagentoStructShoppingCartPaymentEntity',
  'shoppingCartPaymentMethodEntity' => 'MagentoStructShoppingCartPaymentMethodEntity',
  'shoppingCartPaymentMethodResponseEntityArray' => 'MagentoStructShoppingCartPaymentMethodResponseEntityArray',
  'shoppingCartProductEntity' => 'MagentoStructShoppingCartProductEntity',
  'shoppingCartShippingMethodEntity' => 'MagentoStructShoppingCartShippingMethodEntity',
  'shoppingCartTotalsEntity' => 'MagentoStructShoppingCartTotalsEntity',
  'short' => 'MagentoStructShort',
  'storeEntity' => 'MagentoStructStoreEntity',
  'string' => 'MagentoStructString',
  'time' => 'MagentoStructTime',
  'token' => 'MagentoStructToken',
  'unsignedByte' => 'MagentoStructUnsignedByte',
  'unsignedInt' => 'MagentoStructUnsignedInt',
  'unsignedLong' => 'MagentoStructUnsignedLong',
  'unsignedShort' => 'MagentoStructUnsignedShort',
);
	}
}
?>